{% set name = "libtheora" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.xiph.org/releases/theora/{{ name }}-{{ version }}.tar.gz
  sha256: 279327339903b544c28a92aeada7d0dcfd0397b59c2f368cc698ac56f515906e

build:
  number: 0
  run_exports:
    # http://upstream.rosalinux.ru/versions/libtheora.html
    # No release in ~8 years. Keep default pinning
    - {{ pin_subpackage('libtheora') }}
  skip: True  # [win and vc<14]

requirements:
  build:
    - pkg-config
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - autoconf              # [unix]
    - automake              # [unix]
    - make                  # [unix]
    - libtool               # [unix]
    - cmake                 # [win]
    - ninja-base            # [win]
  host:
    - libogg  {{ libogg }}
    - libvorbis  {{ libvorbis }}  # [unix]
  run:
    - {{ pin_compatible('libogg') }}
    - libvorbis             # [unix]

test:
  commands:
    # Verify libraries.
    {% set libtheora_libs = [
        "theora",
        "theoradec",
        "theoraenc"
    ] %}
    {% for each_libtheora_lib in libtheora_libs %}
    - test -f ${PREFIX}/include/theora/{{ each_libtheora_lib }}.h  # [unix]
    - test -f ${PREFIX}/lib/lib{{ each_libtheora_lib }}.a  # [unix]
    - test -f ${PREFIX}/lib/lib{{ each_libtheora_lib }}${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\\theora\\{{ each_libtheora_lib }}.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\{{ each_libtheora_lib }}.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\{{ each_libtheora_lib }}.dll exit 1  # [win]
    {% endfor %}

about:
  home: https://theora.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: 
    - COPYING
    - LICENSE
  summary: Theora is a free and open video compression format from the Xiph.org Foundation.
  description: |
    Theora was Xiph.Org's first publicly released video codec, intended for use within 
    the Foundation's Ogg multimedia streaming system. Theora is derived directly from On2's VP3 codec, 
    adds new features while allowing it a longer useful lifetime.
  dev_url: https://github.com/xiph/theora
  doc_url: https://theora.org/doc/libtheora-1.1/index.html

extra:
  recipe-maintainers:
    - bgruening
    - dschreij
