# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "amDbgr6PZ4i69HXujkRCbcYKWiT/6u67Xx7n+Rm6baiwaCRDl1SrL7gYnUgTHWOSwEZy8FVf5zbHSaAYf5LCNqz9tu8RJOnR2j6vDhoKw6TUJUy3mmrt6zXH/tRaZbfFwWzVTw/5vGpaA+MzEJILuJhfRgzDG3ZaS5yq72J1J3lLNs1pI4lHDBUsl+HtEWOBofLoTLjth0g0wG7PmJTd0WR5N7L5slmyJ6iUN4iJ1ZU6cTxB7WLB9b7aMH9DwPwKDsczyS6dPkTT3HshdDgDv2rC8VfoBMHiLpTZKQWMnM/t/dC+4yNvr3lpU/lkBGLhf04cM0FsKF8VGBF7N10Lm1DZKJfHQqNm+8E3HKC/QRikYvHY559ljjlRBKqEgFkmiA7kw6f3c6BjgoSxNfCG4KnT31OUy4hisLA+TthGk7Edxga+mV7M5L5D5XMWaFgDUrBW+ky0hmlr6t6JYA/0v/4E9AYP+PtK1enZttmxqXskJp/aVe876kHv8Mt9a2hnoSSBrjFywyBhXX+5sWGp78CY5C/lScoV9TVU8iu4nhEcSRc4qy6WYmdp81tdkr+rnV8fcyoc6fgjQfPaL19M4BEgI9ICgIQVmhWlf9GOtipvDgu7n+opTnBHklMhx4WfgxSx48xhFzm2aPlfvm4fmHgMft7jL1Y0W40sivz3zQA="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
