travis:
  secure:
    BINSTAR_TOKEN: Rpup15LGDb/c4p43U8fFaAbPNyNytiytiLOp+yBOqFxplMVQngQD2LTIqHLh3wuJ7d6UaeXUA7cfcYBaWih/Wkje7eb2Ouv2Xg4B6acLbW1VENWl4RcsQxgI6IXNiJLUo9zczecsxQH4UNEXZNUsgK6TTz98KV7AwdjoPTkwWPP0az7scw0Gndhp1sR11Wt8WwKS7Fd7loZ9dEw3wYCxu9IYiA89AEye764EBCPKD4A1L2di1x2Aq3ZCPDnve2cQyIlhyNfd5ybeaninZi1u+KrQONFt7qdlBQkA8TEHX2uCEFXVfxTpfdA5oAHFH3RxQ4paNI9zttr3iiq0HwOy8QtU1hcKHp1NKbcCutKH6kDPAOTrpBr5AXs/ry4YGa2NPYLs60keWjkl2UgVaO4Z2TuLUdH9xwkuDRY9w58JAUNlcazZ8ta73ULL/nQxljlxiDkAiYnv8S0q6X82R3Dzi5S7dEH27xDJmhN2irBE+elJgQY2fx4KxRNITyBRat5yupbirZTweoUnX1tDT4TrXhTmMvXcys2ogYW8SM+W/Kjr08RbTjH9n8PIKUUK2alN2you0zry6LbCfSiBIKzmfPg9wxcbRYML2HSJVetC6B8xgE+OOXlxRKiO2rXpUiBjknhQHHiBPVqovNTkFFrXMAsu5CKVPYEgVTLeDlcF50M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
