travis:
  secure:
    BINSTAR_TOKEN: amDbgr6PZ4i69HXujkRCbcYKWiT/6u67Xx7n+Rm6baiwaCRDl1SrL7gYnUgTHWOSwEZy8FVf5zbHSaAYf5LCNqz9tu8RJOnR2j6vDhoKw6TUJUy3mmrt6zXH/tRaZbfFwWzVTw/5vGpaA+MzEJILuJhfRgzDG3ZaS5yq72J1J3lLNs1pI4lHDBUsl+HtEWOBofLoTLjth0g0wG7PmJTd0WR5N7L5slmyJ6iUN4iJ1ZU6cTxB7WLB9b7aMH9DwPwKDsczyS6dPkTT3HshdDgDv2rC8VfoBMHiLpTZKQWMnM/t/dC+4yNvr3lpU/lkBGLhf04cM0FsKF8VGBF7N10Lm1DZKJfHQqNm+8E3HKC/QRikYvHY559ljjlRBKqEgFkmiA7kw6f3c6BjgoSxNfCG4KnT31OUy4hisLA+TthGk7Edxga+mV7M5L5D5XMWaFgDUrBW+ky0hmlr6t6JYA/0v/4E9AYP+PtK1enZttmxqXskJp/aVe876kHv8Mt9a2hnoSSBrjFywyBhXX+5sWGp78CY5C/lScoV9TVU8iu4nhEcSRc4qy6WYmdp81tdkr+rnV8fcyoc6fgjQfPaL19M4BEgI9ICgIQVmhWlf9GOtipvDgu7n+opTnBHklMhx4WfgxSx48xhFzm2aPlfvm4fmHgMft7jL1Y0W40sivz3zQA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
